version: "3.0"

services:
  terraform_aws_template:
    container_name: terraform_aws_template
    image: terraform_aws_template
    platform: linux/amd64
    build:
      context: ./
    volumes:
        - ./:/terraform
    entrypoint: "/bin/sh"
    env_file:
      - .env
    tty: true
    working_dir: /terraform
